#!/bin/sh

if [ $# -eq 1 ]; then
	echo "Reading args as one string..."
	str=$(printf "%s\n" "$1")
	IFS=$'\n'
	for file in $str; do
		echo "$file"
		fvp -v - "$file"
	done
	exit 1
fi

for file in "$@"; do
	echo "$file"
	fvp -v - "$file"
	if [ $? -ne 0 ]; then
		break
	fi
done
