#!/bin/sh

llmb() {
	llmp "$1" athena-v4.Q8_0.gguf >> res
	llmp "$1" chronos-hermes-13b-v2.Q8_0.gguf >> res
	llmp "$1" mistral-11b-cc-air-rp.Q8_0.gguf >> res
	llmp "$1" noromaid-13b-v0.1.1.q8_0.gguf >> res
	llmp "$1" stheno-l2-13b.Q8_0.gguf >> res
}

llmbr() {
	unset LLM_ARGS
	llmp "$1" athena-v4.Q8_0.gguf > res
	sed -i '1,/### Response:/d' res
	echo -e "Athena's responce:\n$(cat res)" > res
	sed -i 's/### Response://g' res
	res1="$(cat res)
"
	echo "$res1" > res1
	llmp "$1" mistral-11b-cc-air-rp.Q8_0.gguf > res
	sed -i '1,/### Response:/d' res
	echo -e "Mistral's responce:\n$(cat res)" > res
	sed -i 's/### Response://g' res
	res1="${res1}$(cat res)
"
	echo "$res1" > res1
	llmp "$1" stheno-l2-13b.Q8_0.gguf > res
	sed -i '1,/### Response:/d' res
	echo -e "Stheno's responce:\n$(cat res)" > res
	sed -i 's/### Response://g' res
	res1="${res1}$(cat res)
"
	echo "$res1" > res1
	llmp "$1" model_007_13b_v2_Q5_K_M.gguf > res
	sed -i '1,/### Response:/d' res
	echo -e "Model007's responce:\n$(cat res)" > res
	sed -i 's/### Response://g' res
	res1="${res1}$(cat res)
"
	echo "$res1" > res1
	llmml "$1" dolphin-2_2-yi-34b.Q4_K_M.gguf > res
	sed -i '1,/<|im_start|>assistant/d' res
	echo -e "Yai's responce:\n$(cat res)" > res
	sed -i 's/<|im_end|>//g' res
	res1="${res1}$(cat res)
"
	echo "$res1" > res1
	llmml "$1" causallm_14b.Q8_0.gguf > res
	sed -i '1,/<|im_start|>assistant/d' res
	echo -e "Casual's responce:\n$(cat res)" > res
	sed -i 's/<|endoftext|>//g' res
	res1="${res1}$(cat res)
"
	echo "$res1" > res1
	export LLM_ARGS="-c 16384"
	llmp "$1
Evaluate and fact check the responce(s). Identify what is most likely true. Then summarize the key ideas from the responce(s).
$res1" sciphi-self-rag-mistral-7b-32k.Q8_0.gguf > res
	sed -i '1,/### Response:/d' res
	echo -e "Sciphi's assessment responce:\n$(cat res)" > res
	sed -i 's/### Response://g' res
	res1="${res1}$(cat res)
"
	echo "$res1" > res1
	echo "$1" > res
	echo "$res1" >> res
}
