#!/bin/sh -e
# Enter a kiss chroot

log() {
    printf '\033[32m->\033[m %s.\n' "$*"
}

die() {
    log "$*" >&2
    exit 1
}

clean() {
    log Unmounting host filesystems; {
        umount "$1/tmp" ||:
        umount "$1/run" ||:
        umount "$1/dev/pts" ||:
        umount "$1/dev/shm" ||:
        umount "$1/dev"  ||:
        umount "$1/proc" ||:
        umount "$1/sys"  ||:
    }

    log Cleaning leftover host files; {
        rm -f "$1/etc/resolv.conf"
    }
}

fullpath() {
        f=$@;
        if [ -d "$f" ]; then
                base="";
                dir="$f";
        else
                base="/$(basename "$f")";
                dir=$(dirname "$f");
        fi;
        dir=$(\cd "$dir" && pwd);
        echo "$dir$base"
}

mounted() {
    # This is a pure shell mountpoint implementation. We're dealing
    # with basic (and fixed/known) input so this doesn't need to
    # handle more complex cases.
    [ -e "$1" ]         || return 1
    [ -e /proc/mounts ] || return 1

    while read -r _ target _; do
        [ "$target" = "$1" ] && return 0
    done < /proc/mounts

    return 1
}

[ -z "$1" ]        && die Need a path to the chroot
[ -d "$1" ]        || die Given path does not exist
[ -d "$1/etc" ]    || die Given path does not contain /etc
[ "$(id -u)" = 0 ] || die Script needs to be run as root

trap 'clean "$1"' EXIT INT

log Mounting /dev, /proc and /sys from host; {
    dev=$(fullpath "$1/dev")
    proc=$(fullpath "$1/proc")
    sys=$(fullpath "$1/sys")
    shm=$(fullpath "$1/dev/shm")
    pts=$(fullpath "$1/dev/pts")
    tmp=$(fullpath "$1/tmp")
    run=$(fullpath "$1/run")
    
    mounted "$dev"  || mount -o bind /dev "$dev"  ||:
    mounted "$proc" || mount -t proc proc "$proc" ||:
    mounted "$sys"  || mount -t sysfs sys "$sys"  ||:

    mounted "$shm" || mount -t tmpfs shmfs "$shm"  ||:

    mounted "$pts" || mount -o bind /dev/pts "$pts"  ||:

    mounted "$tmp" || mount -o mode=1777,nosuid,nodev -t tmpfs tmpfs "$tmp"  ||:

    mounted "$run" || mount -t tmpfs tmpfs "$run"  ||:
}

log Copying /etc/resolv.conf from host; {
    cp -f /etc/resolv.conf "$1/etc" ||:
}

log Entering chroot; {
    chroot "$1" /usr/bin/env -i \
        HOME=/root \
        TERM="$TERM" \
        SHELL=/bin/sh \
        LOGNAME=root \
        USER=root \
        CFLAGS="${CFLAGS:--march=x86-64 -mtune=generic -pipe -Os}" \
        CXXFLAGS="${CXXFLAGS:--march=x86-64 -mtune=generic -pipe -Os}" \
        MAKEFLAGS="${MAKEFLAGS:--j$(nproc 2>/dev/null || echo 1)}" \
        DISPLAY="$DISPLAY" \
        /bin/sh -l
}
